# Theme
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "dark"

# Site Settings
title: ejayledesma
description: This is my personal site.
subtitle: a personal site
name: Ejay Ledesma
url: "https://ejayledesma.github.io"
repository: "ejayledesma/ejayledesma.github.io"
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Site Author
author:
  name: "Ejay Ledesma"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "A Pinoy Software Engineer who wants to learn and share stuff"
  location: "Philippines"
  email: "ejayledesma@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ejayledesma"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ejayledesma/"
    - label: "Goodreads"
      icon: "fab fa-fw fa-goodreads"
      url: "https://www.goodreads.com/user/show/47262940-ejay-the-casual-reader"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ejayledesma"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ejayledesma/"

# reading files
include:
  - _pages

exclude: [vendor]

# commenting
comments:
  provider: "facebook"
  facebook:
    #appid: # optional
    num_posts: 5
    colorscheme: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-feed

# defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: project
    values:
      layout: single
      author_profile: false
      share: true

collections:
  project:
    output: true
    permalink: /:collection/:path/